config/routes.rb
Rails.application.routes.draw do
  root 'place_of_interests#index'
  resources :place_of_interests
  resources :national_parks

end

app/models/national_park.rb
class NationalPark < ActiveRecord::Base
  has_many :places_of_interest
end

app/models/place_of_interest.rb
class PlaceOfInterest < ActiveRecord::Base
  belongs_to :national_park
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/national_parks_controller.rb
class NationalParksController < ApplicationController
  before_action :set_national_park, only: [:show, :edit, :update, :destroy]

  # GET /national_parks
  # GET /national_parks.json
  def index
    @national_parks = NationalPark.all
  end

  # GET /national_parks/1
  # GET /national_parks/1.json
  def show
  end

  # GET /national_parks/new
  def new
    @national_park = NationalPark.new
  end

  # GET /national_parks/1/edit
  def edit
  end

  # POST /national_parks
  # POST /national_parks.json
  def create
    @national_park = NationalPark.new(national_park_params)

    respond_to do |format|
      if @national_park.save
        format.html { redirect_to @national_park, notice: 'National park was successfully created.' }
        format.json { render :show, status: :created, location: @national_park }
      else
        format.html { render :new }
        format.json { render json: @national_park.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /national_parks/1
  # PATCH/PUT /national_parks/1.json
  def update
    respond_to do |format|
      if @national_park.update(national_park_params)
        format.html { redirect_to @national_park, notice: 'National park was successfully updated.' }
        format.json { render :show, status: :ok, location: @national_park }
      else
        format.html { render :edit }
        format.json { render json: @national_park.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /national_parks/1
  # DELETE /national_parks/1.json
  def destroy
    @national_park.destroy
    respond_to do |format|
      format.html { redirect_to national_parks_url, notice: 'National park was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_national_park
      @national_park = NationalPark.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def national_park_params
      params.require(:national_park).permit(:name, :description)
    end
end

app/controllers/place_of_interests_controller.rb
class PlaceOfInterestsController < ApplicationController
  before_action :set_place_of_interest, only: [:show, :edit, :update, :destroy]

  # GET /place_of_interests
  # GET /place_of_interests.json
  def index
    @place_of_interests = PlaceOfInterest.all
  end

  # GET /place_of_interests/1
  # GET /place_of_interests/1.json
  def show

  end

  def next_place
    @place_of_interest_name = PlaceOfInterest.order("RANDOM()").first.name
    @place_of_interest_address = PlaceOfInterest.order("RANDOM()").address
    @place_of_interest_latitude = PlaceOfInterest.order("RANDOM()").latitude
    @place_of_interest_longitude = PlaceOfInterest.order("RANDOM()").longitude
  end

  # GET /place_of_interests/new
  def new
    @place_of_interest = PlaceOfInterest.new
  end

  # GET /place_of_interests/1/edit
  def edit
  end

  # POST /place_of_interests
  # POST /place_of_interests.json
  def create
    @place_of_interest = PlaceOfInterest.new(place_of_interest_params)

    respond_to do |format|
      if @place_of_interest.save
        format.html { redirect_to @place_of_interest, notice: 'Place of interest was successfully created.' }
        format.json { render :show, status: :created, location: @place_of_interest }
      else
        format.html { render :new }
        format.json { render json: @place_of_interest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /place_of_interests/1
  # PATCH/PUT /place_of_interests/1.json
  def update
    respond_to do |format|
      if @place_of_interest.update(place_of_interest_params)
        format.html { redirect_to @place_of_interest, notice: 'Place of interest was successfully updated.' }
        format.json { render :show, status: :ok, location: @place_of_interest }
      else
        format.html { render :edit }
        format.json { render json: @place_of_interest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /place_of_interests/1
  # DELETE /place_of_interests/1.json
  def destroy
    @place_of_interest.destroy
    respond_to do |format|
      format.html { redirect_to place_of_interests_url, notice: 'Place of interest was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place_of_interest
      @place_of_interest = PlaceOfInterest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def place_of_interest_params
      params.require(:place_of_interest).permit(:name, :latitude, :longitude, :address, :national_park_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/national_parks_helper.rb
module NationalParksHelper
end

app/helpers/place_of_interests_helper.rb
module PlaceOfInterestsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BlairWitch</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/national_parks/_form.html.erb
<%= form_for(@national_park) do |f| %>
  <% if @national_park.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@national_park.errors.count, "error") %> prohibited this national_park from being saved:</h2>

      <ul>
      <% @national_park.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/national_parks/edit.html.erb
<h1>Editing National Park</h1>

<%= render 'form' %>

<%= link_to 'Show', @national_park %> |
<%= link_to 'Back', national_parks_path %>

app/views/national_parks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Add your National Parks destination</h1>

  <img src="http://www.neiltortorella.com/images/rv-with-garage-1328-rv-garages-carports-1628-x-1085.jpg">


<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @national_parks.each do |national_park| %>
      <tr>
        <td><%= national_park.name %></td>
        <td><%= national_park.description %></td>
        <td><%= link_to 'Show', national_park %></td>
        <td><%= link_to 'Edit', edit_national_park_path(national_park) %></td>
        <td><%= link_to 'Destroy', national_park, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New National park', new_national_park_path %>

app/views/national_parks/new.html.erb
<h1>New National Park</h1>

<%= render 'form' %>

<%= link_to 'Back', national_parks_path %>

app/views/national_parks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @national_park.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @national_park.description %>
</p>

<%= link_to 'Edit', edit_national_park_path(@national_park) %> |
<%= link_to 'Back', national_parks_path %>

app/views/place_of_interests/_form.html.erb
<%= form_for(@place_of_interest) do |f| %>
  <% if @place_of_interest.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@place_of_interest.errors.count, "error") %> prohibited this place_of_interest from being saved:</h2>

      <ul>
      <% @place_of_interest.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :national_park_id %><br>
    <%= f.text_field :national_park_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/place_of_interests/edit.html.erb
<h1>Editing Place Of Interest</h1>

<%= render 'form' %>

<%= link_to 'Show', @place_of_interest %> |
<%= link_to 'Back', place_of_interests_path %>

app/views/place_of_interests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Place Of Interests!</h1>
 <p> Use this guide to find your adventure</p>

 <img src= "http://yesofcorsa.com/wp-content/uploads/2015/08/3366_yellowstone_national_park.jpg">

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Address</th>
      <th>National park</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @place_of_interests.each do |place_of_interest| %>
      <tr>
        <td><%= place_of_interest.name %></td>
        <td><%= place_of_interest.latitude %></td>
        <td><%= place_of_interest.longitude %></td>
        <td><%= place_of_interest.address %></td>
        <td><%= place_of_interest.national_park %></td>
        <td><%= link_to 'Show', place_of_interest %></td>
        <td><%= link_to 'Edit', edit_place_of_interest_path(place_of_interest) %></td>
        <td><%= link_to 'Destroy', place_of_interest, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Place of interest', new_place_of_interest_path %>

app/views/place_of_interests/new.html.erb
<h1>New Place Of Interest</h1>

<%= render 'form' %>

<%= link_to 'Back', place_of_interests_path %>

app/views/place_of_interests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @place_of_interest.name %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @place_of_interest.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @place_of_interest.longitude %>
</p>

<p>
  <strong>Address:</strong>
  <%= @place_of_interest.address %>
</p>

<p>
  <strong>National park:</strong>
  <%= @place_of_interest.national_park %>
</p>

<%= link_to 'Edit', edit_place_of_interest_path(@place_of_interest) %> |
<%= link_to 'Back', place_of_interests_path %>